version: 2.1
executors:
  ubuntu:
    machine:
      image: ubuntu-1604:202007-01
jobs:
  image-build:
    executor: ubuntu
    steps:
      - checkout
      - run:
          name: image build
          command: docker build --cache-from nginx --build-arg GCP_CREDS="${GOOGLE_CREDENTIALS}" -t kw-datalake-dlp .
workflows:
     jobs:
      - image-build
